services:
  postgresdb:
    container_name: roomerfind-db
    hostname: roomerfind-db
    image: postgres
    environment:
      POSTGRES_DB: "roomerfindDB"
      POSTGRES_USER: "roomerfind"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - roomer-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U roomerfind -d roomerfindDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  backend:
    container_name: roomerfind-app
    image: ${BACKEND_IMAGE}
    restart: always
    ports:
      - "8083:8082"
    environment:
      DB_URL: "jdbc:postgresql://roomerfind-db:5432/roomerfindDB"
      DB_USER: "roomerfind"
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - avatars:/avatars
    networks:
      - postgres
    depends_on:
      - postgresdb

volumes:
  roomer-data:
  avatars:

networks:
  postgres:
    driver: bridge