services:
  postgresdb:
    container_name: roomerfind-db
    hostname: roomerfind-db
    image: postgres
    environment:
      POSTGRES_DB: "roomerfindDB"
      POSTGRES_USER: "roomerfind"
      POSTGRES_PASSWORD: "EyJgoLaw9z5RgX9"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - roomer-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U roomerfind -d roomerfindDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: roomerfind-db-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@roomerfind.ru"
      PGADMIN_DEFAULT_PASSWORD: "roomerfind-admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
    depends_on:
      - postgresdb

  backend:
    container_name: roomerfind-app
    build: ./backend
    restart: on-failure
    ports:
      - "8083:8082"
    environment:
      DB_URL: "jdbc:postgresql://roomerfind-db:5432/roomerfindDB"
      DB_USER: "roomerfind"
      DB_PASSWORD: "EyJgoLaw9z5RgX9"
    volumes:
      - avatars:/avatars
    networks:
      - postgres
    depends_on:
      - postgresdb
      - pgadmin

volumes:
  roomer-data:
  pgadmin-data:
  avatars:

networks:
  postgres:
    driver: bridge